import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

from dot_env import MY_EMAIL_FOR_CONTACT, EMAIL_PASSWORD


def send_contact_email(data):
    msg = MIMEMultipart()
    msg['From'] = data['email']
    msg['To'] = MY_EMAIL_FOR_CONTACT
    msg['Subject'] = f"New Form Submission: {data['contact_type'].title().upper()} - {data['subject']}"

    # Email body
    body = \
f"""Contact Us form submission received:

📋 CONTACT DETAILS:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Name: {data['name']}
Email: {data['email']}
Type: {data['contact_type'].title()}
Subject: {data['subject']}
Priority: {data['priority'].title()}
Subscribe: {data['subscribe']}
Timestamp: {data['timestamp']}

💬 MESSAGE:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
{data['query']}

🔍 TECHNICAL INFO:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
IP Address: {data['ip_address']}
User Agent: {data['user_agent']}

---------------------------------------------
This email was automatically generated by "mProvMeds":
Support | Contact Form.
"""

    msg.attach(MIMEText(body, 'plain'))

    # Send email
    server = smtplib.SMTP('smtp.gmail.com', 587)
    server.starttls()
    server.login(MY_EMAIL_FOR_CONTACT, EMAIL_PASSWORD)
    text = msg.as_string()
    server.sendmail(MY_EMAIL_FOR_CONTACT, MY_EMAIL_FOR_CONTACT, text)
    server.quit()
